name: simple

on:
  workflow_disoatch:

jobs:
  build:
  runs-on:
    -self-hosted

  steps:

      -uses: actions/checkout@v2
      name: Run a one-line script
      run: 
        echo Hello world!
        slep 15
        echo Goodbye